### ISSUE TITLE
code crashes in the middle of query

### ISSUE THREAD

**Issue by artypoop** [ChinemeremChigbo/discord-mutual-friends-and-servers#6]
I open git cmd
enter `cd C:\Users\artem` [main.py's directory]
use code: `python3 main.py -j True -i "IronScape"`
It starts fine and then crashes midway.

`INFO:root:Processing IronScape server, progress = 1/1 servers 1720/5996 members
INFO:root:Processing IronScape server, progress = 1/1 servers 1721/5996 members
INFO:root:Processing IronScape server, progress = 1/1 servers 1722/5996 members
[2024-07-18 09:50:13] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\artem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 637, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\artem\main.py", line 48, in on_ready
    server_info = await self.get_server_info(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\artem\main.py", line 310, in get_server_info
    member_profile = await server.fetch_member_profile(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\artem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\guild.py", line 2643, in fetch_member_profile
    data = await state.http.get_user_profile(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\artem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 928, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10013): Unknown User
ERROR:discord.client:Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\artem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 637, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\artem\main.py", line 48, in on_ready
    server_info = await self.get_server_info(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\artem\main.py", line 310, in get_server_info
    member_profile = await server.fetch_member_profile(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\artem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\guild.py", line 2643, in fetch_member_profile
    data = await state.http.get_user_profile(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\artem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 928, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10013): Unknown User
[2024-07-18 09:59:54] [INFO    ] discord.gateway: Gateway has successfully RESUMED session 80c0a86f840e6187cdbf839481ef4e91.
INFO:discord.gateway:Gateway has successfully RESUMED session 80c0a86f840e6187cdbf839481ef4e91.
`

**Comment by ChinemeremChigbo** [comment]
Hey! Could you please let me know if the main function here: https://github.com/ChinemeremChigbo/discord-mutual-friends-and-servers/issues/8#issue-2470347109 fixes your issues? Thanks!
