### ISSUE TITLE
'include_servers' doesn't work with spaces or quotes

### ISSUE THREAD

**Issue by zzgames** [ChinemeremChigbo/discord-mutual-friends-and-servers#9]
# Example with quotes:
command: ```python main.py -i 'server'```
output:
```
WARNING:root:Did not find the following servers: {"'server'"} consider choosing from the following servers: { ... }
```

# Example with spaces
command: ``` python main.py -i 'server name' ```
output:
```
WARNING:root:Did not find the following servers: {"'server", "name'"} consider choosing from the following servers: { ... }
```

# The error that I'm getting in both cases:
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-44' coro=<GuildSubscriptions._tick_task() done, defined at C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\state.py:559> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\state.py", line 562, in _tick_task
    await self._flush()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\state.py", line 679, in _flush
    await self._state.ws.bulk_guild_subscribe(payload)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\gateway.py", line 741, in bulk_guild_subscribe
    await self.send_as_json(payload)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\gateway.py", line 659, in send_as_json
    await self.send(utils._to_json(data))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\gateway.py", line 655, in send
    await self.socket.send_str(data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client_ws.py", line 225, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\http_websocket.py", line 726, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\http_websocket.py", line 626, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

**Comment by zzgames** [comment]
Works with double quotes, but in the [README.md](https://github.com/ChinemeremChigbo/discord-mutual-friends-and-servers/blob/029da024211d54b820cc9e98be1a6df08bc90efb/README.md?plain=1#L81C333-L81C337) the example uses single quotes
